language: python
python:
 - "3.6"

 
dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "kxue4-Triangle567"
    token: 
      secure: 927b6a472c99dee445661e165b87b0d44640dd3a
    branches:
      - master


# command to run tests
install:
  - pip install codecov
  
script:
 - coverage run test_triangle.py

after_success:
  - codecov
